### ISSUE TITLE
Missing underflow checks for `builtin sub` on unsigned integers

### ISSUE THREAD

**Issue by jjcnn** [Xfers/StraitsX-tokens#16]
Several transitions have code subtracting two unsigned integers from each other, along the following lines:

```
new_allowed = builtin sub allowance value;
```

However, in only one case is there a preceeding check that `allowance` is greater than or equal to `value`. If such a check is not performed, the application of `sub` may cause an underflow when its arguments are unsigned integers.

**Comment by junhaoyap** [comment]
Resolved the consistency and applied the logic that if a user have 10 minting / allowance value and gets a decrease of 30, it should result in a 0 rather than reverting, this results in an easier usage of the smart contract
