### ISSUE TITLE
Syntax error in xsgd_contract.scilla

### ISSUE THREAD

**Issue by jjcnn** [Xfers/StraitsX-tokens#8]
I am getting the following error from `scilla-checker` when checking xsgd_contract.scilla:

```
contracts/xsgd_contract.scilla:387:4: error: Following a transition definition, the parser expects a transition or a procedure or end of file. 
```

**Comment by junhaoyap** [comment]
Hmm this is strange, on that file, on line 388, there is a new transition being defined

**Comment by jjcnn** [comment]
> Hmm this is strange, on that file, on line 388, there is a new transition being defined

Yes, but that's just where the parser discovers the error. The actual error is the spurious `end` in line 377, which confuses the parser.

That spurious `end` shadows a type error in line 373, BTW.

**Comment by AmritKumar** [comment]
Fixed here: https://github.com/Xfers/XSGD-scilla/pull/14 @junhaoyap
